name: Site Build
on:
  push:
    branches: 
      - gh-pages
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{secrets.GH_TOKEN}}
    - name: Set MkDocs Material Version
      run: echo MKDOCS_MATERIAL_VERSION=latest >> $GITHUB_ENV

    - name: Build the site with squidfunk/mkdocs-material container
      run: |
        docker pull squidfunk/mkdocs-material:$MKDOCS_MATERIAL_VERSION
        docker run -v ${{ github.workspace }}/docs-site:/docs squidfunk/mkdocs-material:$MKDOCS_MATERIAL_VERSION build
    - name: Clean-up and Copy Build Output
      run: |
        mkdir ../temp/
        mv * ../temp/
        mv ../temp/index.yaml .
        mv ../temp/docs-site/ .
        mkdir assets
        mv ../temp/assets/images assets/
        mv ../temp/CNAME .
        rm -rf ../temp/
        cp -a docs-site/site/. .
    - name: Git Commit and Push
      run: |
        git config user.name ${{secrets.GH_USER_NAME}}
        git config user.email ${{secrets.GH_USER_EMAIL}}
        git add .
        git commit -m "Site content updated - ci skip"
        git push origin gh-pages
